### ISSUE TITLE
getting error while typing npm install

### ISSUE THREAD

**Issue by sriniketan18** [insidesherpa/JPMC-tech-task-3#13]
![Capture](https://user-images.githubusercontent.com/43096385/80600657-5e264200-8a4a-11ea-8463-f6f37d537502.PNG)
![Capture1](https://user-images.githubusercontent.com/43096385/80600891-a8a7be80-8a4a-11ea-814c-37be69409392.PNG)
The above two links shows the error that I am getting while I run npm install
Can anyone tell me how to resolve it.

**Comment by 1UC1F3R616** [comment]
@sriniketan18 Download the npm_module from the given link in the ppt. I had similar issue.
You can use the npm_module folder of task-2 aswell.

**Comment by sriniketan18** [comment]
@1UC1F3R616 I downloaded the npm-modules from drive and replaced it andd then when I write the npm start command I am getting an error like this:
C:/Users/Admin/JPMC-tech-task-3/src/Graph.tsx
Type error: Cannot find module '@jpmorganchase/perspective'. TS2307

1 | import React, { Component } from 'react';
2 | import { Table } from '@jpmorganchase/perspective';
| ^
3 | import { ServerRespond } from './DataStreamer';
4 | import { DataManipulator } from './DataManipulator';
5 | import './Graph.css';
