### ISSUE TITLE
npm install showing error

### ISSUE THREAD

**Issue by Shubhraaa** [insidesherpa/JPMC-tech-task-3#27]
![Screenshot (25)](https://user-images.githubusercontent.com/47224990/81917506-20690380-958a-11ea-9382-14660b2f2d12.png)

**Comment by bhavinf** [comment]
I hope you are running your command prompt as an administrator. If yes, try closing the cmd and open it again. After this run the command "npm install" again and then run "npm start". Restarting the command prompt made a difference for me (I don't know how, but it did)

**Comment by rkrahulmishra887** [comment]
can you assign this task to me?
