### ISSUE TITLE
**Important Please help me with this

### ISSUE THREAD

**Issue by JAIS0N** [insidesherpa/JPMC-tech-task-3#30]
![image](https://user-images.githubusercontent.com/46769916/82335623-3c93f700-9a07-11ea-95a3-ca2371159c66.png)
I did everything as said but getting this syntax issue please help

**Comment by SanikaSanaye** [comment]
Can you post a picture of your entire Graph.tsx file?

**Comment by JAIS0N** [comment]
> Can you post a picture of your entire Graph.tsx file?

Thank you so much for your concern!!! The problem was the keyword "const" wasn't declared as a datatype but a normal text instead . I re-typed the whole thing and completed the task received my certificate but forgot  to close the issue
