### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by KapilM16** [insidesherpa/JPMC-tech-task-3#34]
C:\Users\UserName\JPMC-tech-task-3>python datafeed/server.py
  File "datafeed/server.py", line 217
    print 'HTTP server started on port 8080'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('HTTP server started on port 8080')?

Please help. I am getting this while completing both task 2 and 3

**Comment by rkrahulmishra887** [comment]
can you assign me for this task?

**Comment by KapilM16** [comment]
Hey thanks buddy, but i solved and completed the task !
