### ISSUE TITLE
row is not assignable to table

### ISSUE THREAD

**Issue by Mars1998** [insidesherpa/JPMC-tech-task-3#42]
![error](https://user-images.githubusercontent.com/39759879/84422412-9a001a00-ac3a-11ea-8a6e-124818a24c35.png)

**Comment by kennytanggg** [comment]
hi @Mars1998 I'm having a similar issue.  How did you resolve this one?
Please see this link below
[https://github.com/insidesherpa/JPMC-tech-task-3/issues/59](https://github.com/insidesherpa/JPMC-tech-task-3/issues/59)

**Comment by neerraj26** [comment]
Hi @Mars1998 How did you resolve the issue? I'm facing a similar one.
#63
