### ISSUE TITLE
 Failed at the bank-merge-co-task-3@0.1.0 start script.

### ISSUE THREAD

**Issue by sushilca98** [insidesherpa/JPMC-tech-task-3#9]
Hello Sir,

I am having issues with Bank-merge-co-task-3.
Please see attached screenshot.
It says :
 **npm WARN Local package.json exists, but node_modules missing, did you mean to install?**
But I have installed node_modules. 
For reference I have attached different screenshot for the location of installed node_modules.
So, please check whether it's installed properly or installed in wrong location.
Please help me to solve these issues.

Best Regards,
Sushil
![Error Task 3](https://user-images.githubusercontent.com/53387282/70600118-c495eb00-1ba3-11ea-8a80-c5fe5d04bd69.PNG)
![Node_Modules_View 1 A](https://user-images.githubusercontent.com/53387282/70600139-d2e40700-1ba3-11ea-9849-0ecc78aafa99.PNG)
![Node_Modules_View 1 A a](https://user-images.githubusercontent.com/53387282/70600145-d8d9e800-1ba3-11ea-895c-e8881ea84a9b.PNG)

**Comment by jbf-insidesherpa** [comment]
@sushilca98 you're supposed to run **npm install** inside the repository. This will create the repositories own **node_modules** based on the dependencies cited in the package.json of the repo.

**Comment by sushilca98** [comment]
Ok...Thank you.
